In [1]:
import numpy as np

In [2]:
array = np.array(range(5, 10))

print(array)

[5 6 7 8 9]


In [7]:
array_2d = np.array([range(0, 5), range(5, 10)])
print(array_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [12]:
array_2d.shape

(2, 5)

In [13]:
array_2d.size

10

In [15]:
print(array_2d.T)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [5]:
matrix = [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]

row_index = 1  # Index of the row to set to zero

# Set the entire row to zero
matrix[row_index] = [0] * len(matrix[row_index])

print(matrix)

[[1, 2, 3], [0, 0, 0], [1, 2, 3]]
